### ISSUE TITLE
Something about Database.php isn't working right

### ISSUE THREAD

**Issue by yakotta** [yakotta/luxemanagers#24]
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1049] Unknown database 'luxemanagers' in /Users/jenna/Sites/luxemanagers/library/Database.php:57 Stack trace: #0 /Users/jenna/Sites/luxemanagers/library/Database.php(57): PDO->__construct('mysql:dbname=lu...', 'root', 'root', Array) #1 /Users/jenna/Sites/luxemanagers/library/Database.php(65): Database->__construct() #2 /Users/jenna/Sites/luxemanagers/objects/ServiceAPI.php(20): Database::connect() #3 /Users/jenna/Sites/luxemanagers/objects/GeneralRoutes.php(5): ServiceAPI::getServiceList() #4 /Users/jenna/Sites/luxemanagers/library/Route.php(72): GeneralRoutes::webHomePage(Array, '/') #5 /Users/jenna/Sites/luxemanagers/index.php(23): Route::match('/', 'GeneralRoutes::...') #6 {main} thrown in /Users/jenna/Sites/luxemanagers/library/Database.php on line 57

**Comment by yakotta** [comment]
I think it's because i have a new clone of it on a new computer, and when I went to run the migrations at localhost/luxemanagers/migrations, it just redirects me to localhost/luxemanagers/migrations/?url=/migrations. phpmyadmin isn't even showing the databases as existing.

**Comment by yakotta** [comment]
I was able to get rid of that problem by getting the database folder off my backupdrive. But even though phpmyadmin recognizes a luxemanagers folder, it doesn't recognize any of the individual databases to services, migrations, etc, and those don't show up in phpmyadmin, only luxemanagers

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'luxemanagers.services' doesn't exist in /Users/jenna/Sites/luxemanagers/objects/ServiceAPI.php:21 Stack trace: #0 /Users/jenna/Sites/luxemanagers/objects/ServiceAPI.php(21): PDO->query('select * from s...') #1 /Users/jenna/Sites/luxemanagers/objects/GeneralRoutes.php(5): ServiceAPI::getServiceList() #2 /Users/jenna/Sites/luxemanagers/library/Route.php(72): GeneralRoutes::webHomePage(Array, '/') #3 /Users/jenna/Sites/luxemanagers/index.php(23): Route::match('/', 'GeneralRoutes::...') #4 {main} thrown in /Users/jenna/Sites/luxemanagers/objects/ServiceAPI.php on line 21

**Comment by yakotta** [comment]
Now I've found the individual databases in mysql, but they all have the same errors. "No index defined!" "No partitioning defined!" and multiple iterations of 

Warning in ./libraries/controllers/table/TableStructureController.php#1309
Illegal string offset 'Data_length'

Backtrace

./libraries/controllers/table/TableStructureController.php#1265: PMA\libraries\controllers\table\TableStructureController->getTableStats()
./libraries/controllers/table/TableStructureController.php#355: PMA\libraries\controllers\table\TableStructureController->displayStructure(
array,
array,
array,
boolean false,
array,
array,
)
./tbl_structure.php#47: PMA\libraries\controllers\table\TableStructureController->indexAction()

but where the number at the end of ./libraries/controllers/table/TableStructureController.php#1309 changes (#1309, #1312, #1324, etc)

**Comment by yakotta** [comment]
I think I need to just abandon the copies of the database I brought over from the backup and solve the issue of the migrations url redirection so i can just run the migrations again and have a fresh start with this all. i just have no idea where the url redirection is coming from.

**Comment by christhomas** [comment]
I suggest that you open phpmyadmin, delete the luxemanagers database, create a new luxemanagers database (with utf8 encoding), then run all the migrations again. You will lose any data you created manually, but you'll be able to get it all back with an hour of work anyway since there isn't that much data to lose.

1) in your first error: Unknown database 'luxemanagers'
It cannot find the luxemanagers database. You might think it exists, but the computer cannot find it. So a quick check in phpmyadmin, you can see whether there is a luxemanagers database or not. If its missing, then you have lost your database somehow and you might not know why. But the answer is to create a new database and start from scratch.

2) Base table or view not found: 1146 Table 'luxemanagers.services'
Now that you have a luxemanagers database, it cannot find the services table. Again, a quick check into phpmyadmin, you can open the database now, but can you verify there is a services table? If not, then the reason could be that your database is out of date, or too old, perhaps it was created before the services table existed? But perhaps you are using the very latest code. When the services table did exist. So you have a mismatch of versions here. The database might be from January, but the code might be from April.

**Comment by christhomas** [comment]
Regarding the migrations. Perhaps you are using the wrong url. Double check in the router what it says the migrations url should be. I've double checked the code. I can tell you that the url you tried to use was incorrect

**Comment by yakotta** [comment]
Yeah, I should have mentioned, I tried localhost/luxemanagers/admin/migrations, and that gives the same error. Either I import the database from the backup and I get 

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'luxemanagers.migrations' doesn't exist in /Users/jenna/Sites/luxemanagers/library/Migrations.php:11 Stack trace: #0 /Users/jenna/Sites/luxemanagers/library/Migrations.php(11): PDO->query('select filename...') #1 /Users/jenna/Sites/luxemanagers/objects/AdminRoutes.php(16): Migrations::check('/luxemanagers/o...') #2 /Users/jenna/Sites/luxemanagers/library/Route.php(72): AdminRoutes::adminRunMigrations(Array, '/admin/migratio...') #3 /Users/jenna/Sites/luxemanagers/index.php(61): Route::match('/admin/migratio...', 'AdminRoutes::ad...') #4 {main} thrown in /Users/jenna/Sites/luxemanagers/library/Migrations.php on line 11

Or without the backed up databases I get 

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1049] Unknown database 'luxemanagers' in /Users/jenna/Sites/luxemanagers/library/Database.php:57 Stack trace: #0 /Users/jenna/Sites/luxemanagers/library/Database.php(57): PDO->__construct('mysql:dbname=lu...', 'root', 'root', Array) #1 /Users/jenna/Sites/luxemanagers/library/Database.php(65): Database->__construct() #2 /Users/jenna/Sites/luxemanagers/library/Migrations.php(7): Database::connect() #3 /Users/jenna/Sites/luxemanagers/objects/AdminRoutes.php(16): Migrations::check('/Users/jenna/Si...') #4 /Users/jenna/Sites/luxemanagers/library/Route.php(72): AdminRoutes::adminRunMigrations(Array, '/admin/migratio...') #5 /Users/jenna/Sites/luxemanagers/index.php(61): Route::match('/admin/migratio...', 'AdminRoutes::ad...') #6 {main} thrown in /Users/jenna/Sites/luxemanagers/library/Database.php on line 57

At least when I use luxemanagers/migrations, I see the header and footer and things. When I use luxemanagers/admin/migrations, I see a blank page with the error only. The databases themselves, including services, exist, but are all showing the same errors
<img width="1440" alt="screen shot 2018-07-08 at 10 28 49 am" src="https://user-images.githubusercontent.com/16373396/42422417-4b73225e-829a-11e8-91ac-d6dd87a8ec29.png">
<img width="1440" alt="screen shot 2018-07-08 at 10 28 52 am" src="https://user-images.githubusercontent.com/16373396/42422418-4b923e28-829a-11e8-8305-1520424ee4dc.png">

**Comment by christhomas** [comment]
The URL might give the same error, but that's a separate issue. It might be that it doesn't matter what URL you use, they'll all fail because of the underlying problem with the database.

I would first solve the problem with the database, then go back to the migrations url. Because the problem seems that your database is corrupt.

Therefore, I would suggest you go with my initial suggestion to delete/create a new empty database. One which isn't corrupt, or has other problems or other factors that might cause it to fail. Then go back to the migrations problem.

**Comment by yakotta** [comment]
Yes, but I can't create new databases. When I delete the old databases and navigate to luxemanagers/admin/migrations, I get 

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1049] Unknown database 'luxemanagers' in /Users/jenna/Sites/luxemanagers/library/Database.php:57 Stack trace: #0 /Users/jenna/Sites/luxemanagers/library/Database.php(57): PDO->__construct('mysql:dbname=lu...', 'root', 'root', Array) #1 /Users/jenna/Sites/luxemanagers/library/Database.php(65): Database->__construct() #2 /Users/jenna/Sites/luxemanagers/library/Migrations.php(7): Database::connect() #3 /Users/jenna/Sites/luxemanagers/objects/AdminRoutes.php(16): Migrations::check('/Users/jenna/Si...') #4 /Users/jenna/Sites/luxemanagers/library/Route.php(72): AdminRoutes::adminRunMigrations(Array, '/admin/migratio...') #5 /Users/jenna/Sites/luxemanagers/index.php(61): Route::match('/admin/migratio...', 'AdminRoutes::ad...') #6 {main} thrown in /Users/jenna/Sites/luxemanagers/library/Database.php on line 57

I can't seem to get it to work no matter what I do.

**Comment by yakotta** [comment]
So I guess, if I delete the databases because they're corrupt, I need to run migrations to make new databases, right?

So what do I do if the migrations refuse to run?

**Comment by christhomas** [comment]
You don't create new databases with migrations. That is not possible to do.

Open phpmyadmin, delete the luxemanagers database, create a new database, all within phpmyadmin. Use utf8 encoding obviously.

THEN run migrations. I think you are deleting the database, then going to the migrations and then obviously the migrations cannot find the database, because you deleted it. It also can't create the database. So it fails.

**Comment by yakotta** [comment]
No, I know. I did that, went into phpmyadmin, created a new database with utf8_general_ci encoding, but once I get to that point, I can't do anything.

**Comment by yakotta** [comment]
Once I've made that database, I still get errors

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'luxemanagers.services' doesn't exist in /Users/jenna/Sites/luxemanagers/objects/ServiceAPI.php:21 Stack trace: #0 /Users/jenna/Sites/luxemanagers/objects/ServiceAPI.php(21): PDO->query('select * from s...') #1 /Users/jenna/Sites/luxemanagers/objects/GeneralRoutes.php(5): ServiceAPI::getServiceList() #2 /Users/jenna/Sites/luxemanagers/library/Route.php(72): GeneralRoutes::webHomePage(Array, '/') #3 /Users/jenna/Sites/luxemanagers/index.php(23): Route::match('/', 'GeneralRoutes::...') #4 {main} thrown in /Users/jenna/Sites/luxemanagers/objects/ServiceAPI.php on line 21

**Comment by christhomas** [comment]
So, once you created your new database. You go to migrations and it complains that it cannot find the database luxemanagers? Even though you just created it? Or does it give a different error? What error does it give?

**Comment by christhomas** [comment]
ok, you pasted the error whilst I was typing my comment, let me read it.

**Comment by yakotta** [comment]
"So, once you created your new database. You go to migrations and it complains that it cannot find the database luxemanagers? "

Yes, this exactly.

**Comment by christhomas** [comment]
Well, actually thats not the same, because not finding the database entirely is one error, but not finding a table within the database is another error. They're both similar in that something cannot be found. But if the error has changed from

1) I cannot find the database
to
2) I can find the database, but I cannot find the table I am needing inside it

Then you have a different error. Just with a similar message

**Comment by christhomas** [comment]
ok, so what I think is happening, is that you are opening the luxemanagers website, and its recognising the General::webHomePage route as matching and executing it. 

Then if you look at the code for webHomePage, you'll see it attempts to read services from the database, which don't exist, because you have an empty database.

The problem is, you need to execute the migrations route. But for some reason its not matching and its not running the migrations needed for the web site to run correctly.

So now you are back to finding out why the migrations url does not match. Thats the problem now. Once you solve that, the database will be filled with data and it'll function again normally. 

So what url exactly are you attempting to open on your web browser?

**Comment by yakotta** [comment]
localhost/luxemanagers/admin/migrations

**Comment by christhomas** [comment]
Is the code on github updated with the version you are using right now? It seems out of date because I remember we created a php library and refactored this and its not showing me all those changes. Perhaps you can push the code you're working on into the develop branch and I can see what you're actually working with

**Comment by yakotta** [comment]
No, I think this is up to date. This has the updated library. Anything that isn't here is gone because my computer is fucked. The copy I'm working on I cloned directly from github onto another machine.

**Comment by christhomas** [comment]
Oh, thats a shame because we removed the library and put it into your php-library project and used php composer to include it as a dependency into luxemanagers. All of that work is gone? You need to do it over again?

**Comment by yakotta** [comment]
I have a copy of php-library here on github

**Comment by yakotta** [comment]
https://github.com/yakotta/php-library

**Comment by yakotta** [comment]
anything from after the last week of april is gone.

**Comment by christhomas** [comment]
Yeah you have the repository, but none of the work to integrate that with luxemanagers I guess? Cause luxemanagers needed to be modified slightly to pull in php-library

**Comment by yakotta** [comment]
I think we pushed everything we worked on here, so it should all be here. And if not, it's on my harddrive, because I don't think we worked on this since before may

**Comment by christhomas** [comment]
I have it all on my computer at home, but that'll have to wait to give it back to you. I don't want you to lose all that work just because your computer had problems.

Anyway, so it appears there is something wrong with the routing. I wonder how to fix it? Remember the old plan? var dump everything? So lets start with that.

Above the line 23 which has "Route::match("/", "GeneralRoutes::webHomePage")" You should do the following:

var_dump($_GET);
die("DEAD");

Then we can see what the "url" field is and see why its not matching. I have a suspicion that the /luxemanagers/ at the beginning of your migrations url is causing the problem.

I never had this problem because I wasn't putting /luxemanagers/ at the beginning of the urls in my web browser, because of the different way that I ran the project on my computer

**Comment by yakotta** [comment]
well if you have it, i have it, because i don't think we've touched it since april 24 (the last commit pushed to php-library) and my last backup was the same day. 

doing the vardump where you described yields 
array(1) { ["url"]=> string(17) "/admin/migrations" } DEAD

**Comment by christhomas** [comment]
and your url was: http://localhost/luxemanagers/admin/migrations ? 

thats weird, cause it should be "/luxemanagers/admin/migrations" .... so where did the luxemanagers part of the url disappear to?

**Comment by yakotta** [comment]
i don't know. I've been looking through files and I don't know. It cuts luxemanagers out of every url i throw at it

**Comment by christhomas** [comment]
oh I just forgot how the code worked,  but now I remember and its doing that because luxemanagers isn't actually part of the website url, its ignored by the server.

the curious thing is that when I create an empty database, host the website in apache just like you and execute the command

```
curl http://localhost/luxemanagers/admin/migrations
```

I get the output
```
vagrant@ubuntu-xenial:/var/www/html$ curl http://localhost/luxemanagers/admin/migrations
<style type='text/css'>.green {color: green}</style><br />
<b>Fatal error</b>:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'luxemanagers.migrations' doesn't exist in /vagrant/luxemanagers/library/Migrations.php:11
Stack trace:
#0 /vagrant/luxemanagers/library/Migrations.php(11): PDO-&gt;query('select filename...')
#1 /vagrant/luxemanagers/objects/AdminRoutes.php(16): Migrations::check('/vagrant/luxema...')
#2 /vagrant/luxemanagers/library/Route.php(72): AdminRoutes::adminRunMigrations(Array, '/admin/migratio...')
#3 /vagrant/luxemanagers/index.php(61): Route::match('/admin/migratio...', 'AdminRoutes::ad...')
#4 {main}
  thrown in <b>/vagrant/luxemanagers/library/Migrations.php</b> on line <b>11</b><br />
vagrant@ubuntu-xenial:/var/www/html$
```

So it seems that the code I cloned from github just five minutes ago, hosted in an identical environment. Is working just fine as far as this code can go. I do remember we added some logic to create the migrations table automatically when it was not present, so we can easily start with an empty database. But that code is sitting on my computer at home and it appears that you've lost it.

I can't really explain why your code thinks that it should match with the web home route and execute it, I guess you can do some extra debugging, var dump lots of things, go into functions and var dump some variables in there and try to go through the problem step by step to see whether I can narrow it down

**Comment by yakotta** [comment]
I don't understand what you mean by "working just as fine as this code can go." This is the same exact error I'm getting that I haven't been able to figure out.

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'luxemanagers.services' doesn't exist in /Users/jenna/Sites/luxemanagers/objects/ServiceAPI.php:21 Stack trace: #0 /Users/jenna/Sites/luxemanagers/objects/ServiceAPI.php(21): PDO->query('select * from s...') #1 /Users/jenna/Sites/luxemanagers/objects/GeneralRoutes.php(5): ServiceAPI::getServiceList() #2 /Users/jenna/Sites/luxemanagers/library/Route.php(72): GeneralRoutes::webHomePage(Array, '/') #3 /Users/jenna/Sites/luxemanagers/index.php(23): Route::match('/', 'GeneralRoutes::...') #4 {main} thrown in /Users/jenna/Sites/luxemanagers/objects/ServiceAPI.php on line 21

What if I just restore it to an old version long enough to create the tables, then bring it back up to date? Or would that only fix the issue on an individual machine, and this problem would persist anytime I tried to put it somewhere new (like on the internet)?

**Comment by yakotta** [comment]
Okay so I decided to give that a try. I went back to version c0e6254 on Feb 7 and the page was displaying content without throwing errors, but the styling didn't seem to be working. Okay, fine, so I went to luxemanagers/admin/migrations, and all the migrations ran, and going back to the home page, most things looked perfect.
<img width="1440" alt="screen shot 2018-07-09 at 9 47 45 am" src="https://user-images.githubusercontent.com/16373396/42464261-64a3ed1c-835d-11e8-9b90-2cccbd6db97d.png">
<img width="1440" alt="screen shot 2018-07-09 at 9 47 54 am" src="https://user-images.githubusercontent.com/16373396/42464262-65cfc5e4-835d-11e8-8aa7-25d84af697cc.png">
<img width="1440" alt="screen shot 2018-07-09 at 9 48 33 am" src="https://user-images.githubusercontent.com/16373396/42464263-671bda6e-835d-11e8-83a7-b8f3357b8902.png">

The only issues were here: an empty press and services. Services is throwing some kind of error
<img width="1440" alt="screen shot 2018-07-09 at 9 50 37 am" src="https://user-images.githubusercontent.com/16373396/42464352-9e96b3ec-835d-11e8-9d05-87b63b0f3529.png">

But the database tables all appear to be populated as expected, with the exception of services, which doesn't exist.
<img width="1440" alt="screen shot 2018-07-09 at 9 51 54 am" src="https://user-images.githubusercontent.com/16373396/42464405-c4701b8a-835d-11e8-9911-78187e3148b3.png">

So I went back and reran migrations, just to see if that would do anything. Nope.
<img width="1440" alt="screen shot 2018-07-09 at 9 53 12 am" src="https://user-images.githubusercontent.com/16373396/42464454-f2424af6-835d-11e8-891e-16e6265ca736.png">

So I was like, okay, still having problems, but what happens if I bring it back to the current version a32b218 on Mar 5? So I did that, went to localhost/luxemanagers/ and it's throwing the exact same error as before
Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'luxemanagers.services' doesn't exist in /Users/jenna/Sites/luxemanagers/objects/ServiceAPI.php:21
<img width="1440" alt="screen shot 2018-07-09 at 10 01 23 am" src="https://user-images.githubusercontent.com/16373396/42464828-156b6048-835f-11e8-8a7c-cc6cbb01844a.png">

Going to localhost/admin/migrations, it's trying to add the 00 migration, which was already successful, and then throwing a new "Integrity violation" error because it's trying to create a database which already exists
Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '/luxemanagers/objects/../migrations/m_00_migrations.php' for key 'PRIMARY' in /Users/jenna/Sites/luxemanagers/library/Migrations.php:27
<img width="1440" alt="screen shot 2018-07-09 at 9 54 32 am" src="https://user-images.githubusercontent.com/16373396/42464866-33d3d326-835f-11e8-9c76-00021d5c88b6.png">

So it seems that something is really broken about databases, and something is particularly broken about the services database. I can try doing vardumps, but I'm not sure if I should be looking for the issue further back in time?

**Comment by christhomas** [comment]
Ok, but this is a situation where things are working. You can try to look at the migration files and debug why you're not getting what you expect and see how things go. So I think you're good to go on that! Well done!

**Comment by christhomas** [comment]
Maybe you can debug why it's trying to add the 00 migration again. That would be interesting to find out

**Comment by yakotta** [comment]
But things...aren't working? But yeah, var dumps I guess.

**Comment by yakotta** [comment]
No matter where I vardump, it gives the same message:
array(1) { ["url"]=> string(17) "/admin/migrations" } DEAD

so like...I don't understand what I'm supposed to be learning from doing this? All I'm seeing is the url of the page over and over again with no other useful information in the vardumps. Is that a good thing?

**Comment by christhomas** [comment]
Well yeah. You added a die statement right? So of course it will always die and you can't pass that line unless you remove it. Then you can start putting var dumps every couple of lines and dump variables. Results of functions. Everything. Sorry that I didn't say that before. I just thought you'd automatically know that if you have a die startment in your code. It will die and won't continue past that line of code. The only way to pass by it. Would be to remove it and maybe add the die startment later. Then later in the file. The more you debug and probe into the depths of the code.

The debugging strategy is. Move the die statement until after the next block of code in the same file. Then you can add var dumps up until that line and interrogate the code until you know what is happening.

Then you move the die startment a couple of lines down. Again and repeat the process. This idea of using the die as a way to control the execution of your code is quite a basic and rudimentary strategy. But it's also the simplest and easiest way to try to figure out what is going wrong with your code.

**Comment by yakotta** [comment]
No, I knew that about die statements. I guess I just thought $_GET would be more useful. I've been moving the die statements, I guess I just don't know what kind of variables I should be looking at, or even what files I should be looking at. I . tried dumping $_POST as well, but it was always empty.

**Comment by christhomas** [comment]
$_POST Will always be empty, unless when you post a HTML form. Which you aren't doing. So that's unsurprising

**Comment by yakotta** [comment]
Okay so what should I be var dumping? Like which variables, because I’m confused.

**Comment by christhomas** [comment]
I wrote this as a reply, but it appears to not have been sent correctly to github. 

----- Chris Wrote:

everything.

A common strategy is divide and conquer. I'll explain.

You have a broken piece of code, you know it obviously starts at the top and its working, but between the top and bottom its broken.

1) you put a die statement half way down the code, somewhere sensible
2) run the code, if you find you hit the die statement, then from the top until that point, the code is running ok, the problem must be after the die and before the  bottom
3) you move the die half way down again, or somewhere you might suspect there is a problem, put it right after that point in the code
4) run the code again, if you hit the die, then ok, the code is ok up until this point, repeat this until you don't hit the die anymore and your code fails in the unexpected way you are trying to fix.
5) once you have found a piece of code where there might be a problem, you know the last position the die was ok and the current position of the, where inbetween those two lines in the code, there is a problem, say you put the die on line 50, no problem hitting the but, but put it on line 75 and you have an error, but no die happening, you know the problem must exist between line 50 and 75
6) then you have a span of lines, you can try the same strategy again, put it on line 55, then line 60, then line 70, each time refresh the code, try to find a place where the code stops working, then you have a smaller target and search area for debugging.
7) if the line of code you've found, is a function. And you have the code to that function, say its one of your library functions. You can var dump all the parameters you give that function, see if any of them are incorrect. You should know the values you are passing to a function. So when you var dump them, check them with what you expect them to hold. If you are not sure what they should hold, go and find out. You should not be in a position where you cannot be able to mentally determine whether data is wrong or not. Perhaps a variable has a false, or a null, or an empty string. Maybe the function is getting the incorrect parameters.
8) If the parameters you var dumped are not containing what you expect, then you can have something to investigate in more detail, then you can go back up the code and see what set or changed that variables value. Then concentrate your debugging here and see whether a function is not giving the correct result.
9) If the parameters are correct, but your code still fails, then perhaps you should open that code and do the above strategy of putting a die then reloading the code, moving the die downwards and reloading the code again, until you find the offending piece of code.

This was one of the first debugging strategies I learned. It's the quickest to master, the hardest part is when you have to search the code for what changes a variable and seeing whether the values are correct. Because sometimes you get unexpected results and then you have to play with the values and try to understand what effects the outcome of certain php code, sometimes you assume that it should return true, but in your specific case it returns a false. Sometimes these things are hard to find, you just have to keep drilling at it until you crack it and find a reason. But once you do, you'll learn a great deal of valuable information about how the language functions. So don't think its a waste of time to investigate. Sometimes thats how you jump forward in terms of knowledge, by bashing your head against a seemingly impossible task.

Good hunting I guess :)

**Comment by yakotta** [comment]
I understand what you're saying about debugging. What I'm confused about is there's something wrong with the database. So how am I supposed to figure out what that is if I'm just dumping the variables that go into the database?

I just did what you suggested and no variables came up empty strings, false, null, or anything. I've identified the offending pieces of code, but I can't see anything wrong with them other than "the databases aren't behaving correctly."

For luxemanagers/admin/migrations, the broken point comes down to the line `$db->query("insert into migrations set filename='$m'");` in `Migrations::add`. `$m` is just a string containing the migrations name (in this case the first one,  `/luxemanagers/objects/../migrations/m_00_migrations.php`), so unless there's something wrong with the name that I'm not seeing, I'm at a loss.

For just luxemanagers/ the broken point is `return $db->query("select * from services");` in `SerivceAPI::getServiceList`.  If I var dump `$db` I get object(PDO)#3 (0) { } which I don't know enough about to know if that's what it's supposed to be? To me it looks like yet another indication that something is wrong with the database itself. If I comment out `$serviceList = ServiceAPI::getServiceList();` in `GeneralRoutes::webHomePage`, the `$testimonialList` and `$featuredPressList` yield object(PDOStatement)#4 (1) { ["queryString"]=> string(26) "select * from testimonials" } and object(PDOStatement)#7 (1) { ["queryString"]=> string(38) "select * from press where featured = 1" } respectively. This makes sense given the above screenshot where there didn't seem to be anything wrong with the Testimonial or Press parts of the page (except for the fact that the press database is empty, which means the migration m_07_add_initial_press.php didn't run...)

I guess I'm confused why I'm var dumping variables when the error codes seem to pretty clearly identify fucked up tables as the culprits? Either that, or something about the migrations isn't running right.

**Comment by christhomas** [comment]
ok, so for the first part, you've found that there is something broken when it tries to insert into the migrations table right? Well lets take that part on its own, what is the error its giving you? 

If the error is that the migrations table doesn't exist, or it cannot find it. Go to phpmyadmin and verify if the migrations table exists or not. Physically verify you can see it and whether it contains any data.

If it does exist, then thats a harder problem to solve which you can deal with later. But if the table doesn't exist. Then you know the problem. You cannot insert into a table which doesnt exist right?

The problem with the migrations table is that you needed to create it manually. We did solve this problem, but it appears you lost the code.

So please check that first, if the table doesnt exist, then you know you have to create it manually, so go ahead and do that. Otherwise, we can talk about what the other problems are afterwards.

**Comment by yakotta** [comment]
The migrations table exists and is populated with data
<img width="1440" alt="screen shot 2018-07-10 at 8 21 43 am" src="https://user-images.githubusercontent.com/16373396/42520134-63953abc-841a-11e8-9578-da1a7fe33283.png">

**Comment by yakotta** [comment]
Again, the error there is "integrity constraint violation"

Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '/luxemanagers/objects/../migrations/m_00_migrations.php' for key 'PRIMARY' in /Users/jenna/Sites/luxemanagers/library/Migrations.php:27

So I guess the check function is failing. It seems like all my library functions are failing?

**Comment by yakotta** [comment]
Wait hold on there is something janky about the migrations table. Look at the last entry and the first. They're for the same migration file: `/luxemanagers/migrations/m_00_migrations.php` and `/luxemanagers/objects/../migrations/m_00_migrations.php`. 

Did something get messed up when we re-did all the library files? 

Here's the full Migrations code from the library:

```
class Migrations {
    // Checks migrations in the database
    static public function check($m)
    {
        $db = Database::connect();
    
        $m = str_replace($_SERVER["DOCUMENT_ROOT"], "", $m);
    
        $result = $db->query("select filename from migrations where filename = '$m'");
    
        if($result === false) return false;
        
        if($result->num_rows == 0) return false;
        
        return true;
    }
    
    // Adds migrations to the database table 
    static public function add($m)
    {
        $db = Database::connect();
    
        $m = str_replace($_SERVER["DOCUMENT_ROOT"], "", $m);
        
        $db->query("insert into migrations set filename='$m'");
    }
}
```

It seems it's getting a different value of `$m` and it likes that until it doesn't. Migrations::check checks the filename and sees that its different, which triggers the Migrations:add function. but when it goes to add it into the database, it gives that Duplicate entry error. So I wonder what happens if I just strip off the /objects/.. part of `$m`?

**Comment by christhomas** [comment]
Bingo! I knew you realise it the longer you looked at it. 

I would suggest you do the following.

Delete the database. Create a new one. So you start fresh.

Change: $m = str_replace($_SERVER["DOCUMENT_ROOT"], "", $m);

To: $m = basename($m);

Now. Why would we do that? The reason is because if you use basename function. It uses only the filename and not the entire path with the folders and things. If you think about it. We don't care about the path of the file. We only care about the filename itself. Since that's the only part of the file which is interesting and you can only have one filename in a directory with the same name. So it means that migrations will be unique.

You remember why we need to first check the migration exists before we run it? Cause we don't want to run the migration a second time right? So using the filename on it's own means we can still have that uniqueness. Without all the stupid problems with the directory that you've discovered today.

Make the change on both lines. Then run the migrations again. Hopefully that fixes your problem.

Chris

**Comment by yakotta** [comment]
Nope. It's not creating tables. I noticed that with the services table, which is missing as well.

**Comment by yakotta** [comment]
So migrations_00 says:
```
$db = Database::connect();

// here is the query which creates the migrations table
$migrations=<<<QUERY
    create table if not exists migrations (
        filename varchar(255),
        primary key (filename)
    ) Engine=InnoDB, CHARACTER SET UTF8;
QUERY;

// this will pass the create table query to the function
$db->query($migrations);

// this migrations keeps track of the migrations that have been run

return true;
```

But what you get out is 

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'luxemanagers.migrations' doesn't exist in /Users/jenna/Sites/luxemanagers/library/Migrations.php:12 Stack trace: #0 /Users/jenna/Sites/luxemanagers/library/Migrations.php(12): PDO->query('select filename...') #1 /Users/jenna/Sites/luxemanagers/objects/AdminRoutes.php(24): Migrations::check('m_00_migrations...') #2 /Users/jenna/Sites/luxemanagers/library/Route.php(72): AdminRoutes::adminRunMigrations(Array, '/admin/migratio...') #3 /Users/jenna/Sites/luxemanagers/index.php(61): Route::match('/admin/migratio...', 'AdminRoutes::ad...') #4 {main} thrown in /Users/jenna/Sites/luxemanagers/library/Migrations.php on line 12

**Comment by yakotta** [comment]
It clearly says to create the table if it doesn't exist, and I renamed the table in phpmyadmin so migrations _doesn't_ exist. And it's complaining about that and refusing to create it? I'm really lost. Seems like sql is just being a dick tbh.

**Comment by yakotta** [comment]
If I try to run migrations with the correct string for the migrations table name AND a populated migrations table, I go from this
<img width="1440" alt="screen shot 2018-07-10 at 8 58 50 am" src="https://user-images.githubusercontent.com/16373396/42522883-19ac9c0e-8421-11e8-9327-d950292f0883.png">

to this
<img width="1440" alt="screen shot 2018-07-10 at 9 09 34 am" src="https://user-images.githubusercontent.com/16373396/42522903-21e78cb2-8421-11e8-90f9-b2290e521fd2.png">

does that mean anything?

**Comment by christhomas** [comment]
Lets do a thought experiment.

check() takes the filename of a migration file, looks into the migrations table and sees whether the filename you have passed in the $m parameter exists already in the database. Right?

Obviously we only want to run each migration once. So we use the filename as an easy way to know whether a migration has run or not. Did you understand the last email that I sent you about changing it to only use the filename. Give me some feedback about what you understood. Because perhaps we are not on the same page. 

if the migrations table doesn't exist. Then it'll crash, cause this code is trying to look into a non-existent table.

This presents a chicken and the egg problem right? The 00_migrations.php file has the SQL code to create the table. But first, it checks the table that doesnt exist, whether the table that this migration will create has the 00_migrations.php inside it.

See the problem? This is an "edge case" where you need a special logic in order to overcome a special situation like this. That is the code that I have on my computer at home, which you lost somehow.

Even if you might not know how to solve it, do you at least get why this requires a special handling, different from the normal situation where the migrations table has been created and you're simply adding more and more migrations to the database. The creation of the migrations table is a "once in a website" type event. You create it once and you never do it again and it has a special meaning and it has to be the very first step in your process since every step that follows from that point in time, depends on this one single special case.

What do you think?

**Comment by yakotta** [comment]
I think there needs to be a line to check if the table exists before checking if the item is in the table.

**Comment by christhomas** [comment]
Bingo!

**Comment by christhomas** [comment]
Explain why and how you think you'd do that

**Comment by yakotta** [comment]
I used your pull request but had to spend some time figuring out what else was broken. Turns out migration 6 had a bunch of errors that were throwing things off. So there was just lots of fun going on here.

**Comment by yakotta** [comment]
Press and testimonials are still a bit fucked up but whatever

**Comment by yakotta** [comment]
it was all smart quotes. that was the problem. stupid apostrophes.
